name: Bug Report
description: Report a bug with clear steps and behavior comparison
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (Required)
      description: List exact steps to reproduce the bug.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior (Required)
      description: What should have happened?
      placeholder: The app should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior (Required)
      description: What actually happened instead?
      placeholder: Instead, it...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Optional: Add screenshots, logs, or environment info if relevant.  
        ✅ Please check the [Definition of Done](https://github.com/bestSWPteam/RentAssistantApplication/blob/main/CONTRIBUTING.md) before closing the issue.
