name: Technical Task
description: Break down a technical implementation or refactor into actionable steps.
title: "[Tech Task] "
labels: [technical]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What is the purpose of this task? What system or component is involved?
      placeholder: Describe the context or background here...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Plan
      description: Describe how the task will be implemented or structured.
      placeholder: Mention technical details, tools, or files to be modified...

  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks
      description: Write subtasks in markdown format. Example: `- [ ] Do something`
      placeholder: |
        - [ ] Subtask one
        - [ ] Subtask two
        - [ ] Subtask three

  - type: markdown
    attributes:
      value: |
        ✅ Please check the [Definition of Done](https://github.com/bestSWPteam/RentAssistantApplication/blob/main/CONTRIBUTING.md) before closing the issue.
