name: CI/CD NGINX Demo


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Шаг 1: Клонирование репозитория на виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Вход в реестр контейнеров GitHub (GHCR)

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_CD_Token }}

      # Шаг 3: Сборка и отправка Docker-образа

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"