name: CI/CD NGINX Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_name: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_CD_Token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  scan_image:
    name: Scan Image for Vulnerabilities
    runs-on: ubuntu-latest
    needs: build_and_push
    permissions:
      contents: read
      packages: read
      security-events: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_CD_Token }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build_and_push.outputs.image_name }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'
          github-pat: ${{ secrets.CI_CD_Token }}

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  # the stage doesn't work, when app is not hosted
  deploy:
    name: Deploy to Production
    needs: scan_image
    runs-on: self-hosted

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Deploy application
        run: |
          docker stop my-nginx-app || true
          docker rm my-nginx-app || true
          
          docker pull ${{ env.IMAGE_NAME }}:latest
          
          docker run -d --name my-nginx-app -p 80:80 ${{ env.IMAGE_NAME }}:latest